#Workflow name
name: CI/CD Pipeline
on:
  #The manual trigger of workflow that runs when we do something with the repo
  workflow_dispatch:

  #Trigger the workflow on push from the main branch
    push:
      branches:
        - main
jobs:
  #The test jobs that needs to run and go through when pushing
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      #Check-out the repository under, so your workflow can access it
      - uses: actions/checkout@v1
      #Set up the JDK
      - name: setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      #Set up Maven cache
      - name: Cache Maven packages/dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      #Run Tests
      - name: Run Tests
        run: mvn -B test
